spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/banco?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: -1
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        ddl-auto: update  # O create-drop, según tu preferencia
        dialect: org.hibernate.dialect.MySQL8Dialect  # Asegúrate de especificar el dialecto de Hibernate
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    mappings:
      enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
clients:
  service:
    url: "http://localhost:8081"